# Generated by Django 3.0.8 on 2020-07-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogpost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=70)),
                ('title', models.CharField(max_length=500)),
                ('desc', models.CharField(max_length=50000)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
