# Generated by Django 3.0.8 on 2020-07-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_user_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_contact',
            name='num',
            field=models.IntegerField(default=0, max_length=1),
            preserve_default=False,
        ),
    ]
