# Generated by Django 3.0.8 on 2020-07-12 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_user_contact_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_contact',
            name='num',
        ),
    ]
