# Generated by Django 3.0.8 on 2020-07-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_user_contact_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_contact',
            name='slug',
            field=models.CharField(default='', max_length=130),
            preserve_default=False,
        ),
    ]
