# Generated by Django 3.0.8 on 2020-07-12 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_user_contact_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_contact',
            name='slug',
        ),
    ]
